In [8]:
import pandas as pd
base = pd.read_csv("base_dbs/twitter.csv")
base.head()

,Tweet ID,Country,Date,Tweet,Definitely English,Ambiguous,Definitely Not English,Code-Switched,Ambiguous due to Named Entities,Automatically Generated Tweets
0,434215992731136000,TR,2014-02-14,Bugün bulusmami lazimdiii,0,0,1,0,0,0
1,285903159434563584,TR,2013-01-01,Volkan konak adami tribe sokar yemin ederim :D,0,0,1,0,0,0
2,285948076496142336,NL,2013-01-01,Bed,1,0,0,0,0,0
3,285965965118824448,US,2013-01-01,I felt my first flash of violence at some fool...,1,0,0,0,0,0
4,286057979831275520,US,2013-01-01,Ladies drink and get in free till 10:30,1,0,0,0,0,0

In [9]:
temp = base.copy()

In [10]:
temp = temp[temp["Definitely English"] == 1]
temp

,Tweet ID,Country,Date,Tweet,Definitely English,Ambiguous,Definitely Not English,Code-Switched,Ambiguous due to Named Entities,Automatically Generated Tweets
2,285948076496142336,NL,2013-01-01,Bed,1,0,0,0,0,0
3,285965965118824448,US,2013-01-01,I felt my first flash of violence at some fool...,1,0,0,0,0,0
4,286057979831275520,US,2013-01-01,Ladies drink and get in free till 10:30,1,0,0,0,0,0
7,286216100784521216,GB,2013-01-01,Watching #Miranda On bbc1!!! @mermhart u r HIL...,1,0,0,0,0,0
9,286282349925257216,US,2013-01-02,Shopping! (@ Kohl's) http://t.co/I8ZkQHT9,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
10493,774721885049323520,US,2016-09-10,"I'm at Hempstead Hair World in Elmont, NY http...",1,0,0,0,0,1
10494,774775165473488898,US,2016-09-11,Bachelorette 💍💞 @ Laurita Winery https://t.co/...,1,0,0,0,0,0
10495,774787685340868608,PH,2016-09-11,When life gives you Lemon 🍋\nREAD 🤓🤓🤓👌👌👌☝️☝\n-...,1,0,0,0,0,0
10496,774940630824816646,US,2016-09-11,This #job might be a great fit for you: Sr. In...,1,0,0,0,0,1
10497,774941788247298050,TR,2016-09-11,"I'm at @PiazzaAvym in Canik, Samsun w/ @mertar...",1,0,0,0,0,1

In [11]:
temp = temp[['Tweet', 'Date']]
temp

                                                   Tweet        Date
2                                                    Bed  2013-01-01
3      I felt my first flash of violence at some fool...  2013-01-01
4                Ladies drink and get in free till 10:30  2013-01-01
7      Watching #Miranda On bbc1!!! @mermhart u r HIL...  2013-01-01
9              Shopping! (@ Kohl's) http://t.co/I8ZkQHT9  2013-01-02
...                                                  ...         ...
10493  I'm at Hempstead Hair World in Elmont, NY http...  2016-09-10
10494  Bachelorette 💍💞 @ Laurita Winery https://t.co/...  2016-09-11
10495  When life gives you Lemon 🍋\nREAD 🤓🤓🤓👌👌👌☝️☝\n-...  2016-09-11
10496  This #job might be a great fit for you: Sr. In...  2016-09-11
10497  I'm at @PiazzaAvym in Canik, Samsun w/ @mertar...  2016-09-11

[5086 rows x 2 columns]

In [12]:
temp["year"] = temp["Date"].str.split("-", expand=True)[0].astype(int)
temp["decade"] = (temp["year"] // 10) * 10
temp.drop(['Date'], axis=1, inplace=True)
temp.rename(columns={"Tweet": "text"}, inplace=True)
temp.head()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22948\999794312.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["year"] = temp["Date"].str.split("-", expand=True)[0].astype(int)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22948\999794312.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["decade"] = (temp["year"] // 10) * 10
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22948\999794312.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.drop(['Date'], axis=1, inplace=True)
C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22948\999794312.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp.rename(columns={"Tweet": "text"}, inplace=True)

                                                text  year  decade
2                                                Bed  2013    2010
3  I felt my first flash of violence at some fool...  2013    2010
4            Ladies drink and get in free till 10:30  2013    2010
7  Watching #Miranda On bbc1!!! @mermhart u r HIL...  2013    2010
9          Shopping! (@ Kohl's) http://t.co/I8ZkQHT9  2013    2010

In [13]:
temp["category"] = "tweet"
temp.head()

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22948\1896190889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp["category"] = "tweet"

                                                text  year  decade category
2                                                Bed  2013    2010    tweet
3  I felt my first flash of violence at some fool...  2013    2010    tweet
4            Ladies drink and get in free till 10:30  2013    2010    tweet
7  Watching #Miranda On bbc1!!! @mermhart u r HIL...  2013    2010    tweet
9          Shopping! (@ Kohl's) http://t.co/I8ZkQHT9  2013    2010    tweet

In [14]:
df = pd.read_parquet("large_dataset.parquet")
df = pd.concat([df, temp], ignore_index=True)
df.to_parquet("large_dataset.parquet")
df.head()

   decade    year                                               text category
0  2010.0  2013.0                                                Bed    tweet
1  2010.0  2013.0  I felt my first flash of violence at some fool...    tweet
2  2010.0  2013.0            Ladies drink and get in free till 10:30    tweet
3  2010.0  2013.0  Watching #Miranda On bbc1!!! @mermhart u r HIL...    tweet
4  2010.0  2013.0          Shopping! (@ Kohl's) http://t.co/I8ZkQHT9    tweet